upipe-x265: work around x265.h undef warning
Since x265 version 2.8:

x265.h:1880:5: error: 'ENABLE_LIBVMAF' is not defined, evaluates
to 0 [-Werror,-Wundef]