upipe-x265: work around x265.h undef warnings
Since x265 version 2.9:

x265.h:34:5: error: '_MSC_VER' is not defined, evaluates to 0
x265.h:175:5: error: 'X265_DEPTH' is not defined, evaluates to 0