Add support for RTP reordering (hitless switching)
Modified-by: Rafaël Carré <funman@videolan.org>

Fix for upipe_rtp_reorder.c:358:17: error: ‘seqnum’ may be used
uninitialized in this function [-Werror=maybe-uninitialized]
Add missing upump_free()