upipe-pthread: depends on -lpthread
We need to know this when using a static upipe build, else we get:
libupipe_pthread.a(libupipe_pthread_la-uprobe_pthread_upump_mgr.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'

We don't use autoconf's PTHREAD_LIBS because it hides -lpthread behind -pthread